# Generated by Django 5.1 on 2025-09-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.FloatField(help_text='Total amount due for payment', verbose_name='Total Amount Owing (Tsh)'),
        ),
    ]
