# Generated by Django 5.1 on 2025-09-07 16:45

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0002_alter_item_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='get_invoice_slug', unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Invoice Date')),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=7, null=True, unique=True)),
                ('contact_number', models.CharField(max_length=13)),
                ('shipping', models.FloatField(blank=True, default=0.0, verbose_name='Shipping and Handling')),
                ('total', models.FloatField(default=0.0, editable=False, verbose_name='Total Amount (Tsh)')),
                ('grand_total', models.FloatField(default=0.0, editable=False, verbose_name='Grand Total (Tsh)')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.customer', verbose_name='Customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('price_per_item', models.FloatField(default=0.0, verbose_name='Price Per Item (Tsh)')),
                ('total_price', models.FloatField(editable=False, verbose_name='Total Price (Tsh)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='store.item', verbose_name='Product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
