# Generated by Django 5.1 on 2025-08-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.FloatField(editable=False, verbose_name='Grand Total (Tsh)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_per_item',
            field=models.FloatField(verbose_name='Price Per Item (Tsh)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(editable=False, verbose_name='Total Amount (Tsh)'),
        ),
    ]
