# Generated by Django 5.1 on 2025-09-08 17:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('invoice', '0002_invoice_converted_to_invoice_invoice_is_proforma_and_more'),
        ('store', '0002_alter_item_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(blank=True, editable=False, max_length=7, null=True, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Delivery Date')),
                ('contact_number', models.CharField(max_length=13)),
                ('shipping_address', models.TextField(verbose_name='Delivery Address')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preparing', 'Preparing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Delivery Notes')),
                ('converted_to_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_source', to='invoice.invoice')),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('price_per_item', models.FloatField(default=0.0, verbose_name='Price Per Item (Tsh)')),
                ('total_price', models.FloatField(editable=False, verbose_name='Total Price (Tsh)')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.delivery')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='store.item')),
            ],
        ),
    ]
