# Generated by Django 5.1 on 2025-09-08 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_delivery_deliveryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delively_invoice', to='invoice.delivery'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='converted_to_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_invoice', to='invoice.invoice'),
        ),
    ]
