# Generated by Django 5.1 on 2025-09-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='item',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping',
            field=models.FloatField(blank=True, verbose_name='Shipping and Handling'),
        ),
    ]
