# Generated by Django 5.1 on 2025-09-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='item',
            field=models.CharField(max_length=10000),
        ),
    ]
